services:

  main:
    build:
      context: .
      target: base
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/go/src/app
      - ~/go/pkg:/go/pkg
    env_file: .env
    ports:
      - ${HTTP_PORT:-8000}:${HTTP_PORT:-8000}
      - ${DELVE_PORT:-8001}:${DELVE_PORT:-8001}
    depends_on:
      - cockroachdb
    tty: true

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.8
    command: start-single-node --insecure
    ports:
      - ${COCKROACHDB_PORT:-26257}:26257
      - ${COCKROACHDB_CONSOLE_PORT:-8080}:8080
    volumes:
      - cockroachdb:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  cockroachdb:
